version: '3'

services:
    yearning:
        image: yearning:latest
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            MYSQL_USER: yearning
            MYSQL_PASSWORD: ukC2ZkcG_ZTeb
            MYSQL_ADDR: mysql
            MYSQL_DB: yearning
        volumes:
        -   ./install_flag:/opt/install_flag
        ports:
            - 8000:8000
        depends_on:
            - mysql
        restart: always

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
            MYSQL_DATABASE: yearning
            MYSQL_USER: yearning
            MYSQL_PASSWORD: ukC2ZkcG_ZTeb
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
# 默认账号：admin，默认密码：Yearning_admin
